name: locallm
include:
  - volumes.yml
  - networks.yml
services:
  comfyui:
    restart: unless-stopped
    extends: 
      file: services/comfy-ui.yml
      service: comfy-ui
    labels:
      - traefik.enable=true
      - traefik.http.routers.comfyui-dockerml.entrypoints=http
      - traefik.http.routers.comfyui-dockerml.rule=PathPrefix(`/comfyui`)
      - traefik.http.routers.comfyui-dockerml.middlewares=comfyui-prefix@docker
      - traefik.http.middlewares.comfyui-prefix.stripprefix.prefixes=/comfyui
  traefik:
    restart: unless-stopped
    extends:
      file: services/traefik.yml
      service: traefik
    ports:
      - "80:80"
      - "4000:4000"
      - "8000:8000"
    command: 
      - --ping=true
      - --api.debug=true
      - --tracing=true
      - --accesslog=true

  open-webui:
    restart: unless-stopped
    extends:
      file: services/open-webui.yml
      service: open-webui
    environment:
      - ENABLE_RAG_WEB_SEARCH=true
      - RAG_WEB_SEARCH_ENGINE=duckduckgo
      - ENABLE_IMAGE_GENERATION=true
      - IMAGE_GENERATION_ENGINE=comfyui
      - COMFYUI_BASE_URL=http://comfyui:8188
      - ENABLE_OLLAMA_API=false
      - WHISPER_MODEL=large
      - OPENAI_API_BASE_URL=http://litellm:4000/v1
    labels:
      - traefik.enable=true
      - traefik.http.routers.open-webui-dockerml.entrypoints=open-webui
      - traefik.http.routers.open-webui-dockerml.rule=PathPrefix(`/`)
  vllm-mistral7B-instruct:
    restart: unless-stopped
    extends:
      file: services/vllm/mistral-7B-instruct.yml
      service: openai
  vllm-dsr1-qwen7B:
    restart: unless-stopped
    extends:
      file: services/vllm/dsr1-qwen-7B.yml
      service: openai
  lmdeploy-intern25-4B:
    restart: unless-stopped
    extends:
      file: services/lmdeploy/intern25-4B.yml
      service: openai
  llamacpp-exaone:
    restart: unless-stopped
    extends:
      file: services/llamacpp/exaone35-2.4B-instruct.yml
      service: openai
  litellm:
    restart: unless-stopped
    extends:
      file: services/litellm.yml
      service: litellm
    labels:
      - traefik.enable=true
      - traefik.http.routers.litellm-dockerml.entrypoints=openai
      - traefik.http.routers.litellm-dockerml.rule=PathPrefix(`/`)
      #- traefik.http.services.litellm.loadbalancer.server.port=4000

configs:
  litellm_config:
    file: config/litellm.yaml
  traefik_config:
    file: config/traefik.toml
